const experiencesData = [
  {
    id: '0',
    company: 'Davidson',
    title: 'Consulting Engineer',
    actions: ['Client Spuerkeess', 'Signing Pad', 'Corona'],
    outcomes: ['Client en agence peuvent signer par signingpad', 'Moins de papier via le moteur'],
    startDate: '2019-02-15',
    endDate: 'Present',
    tags: ['Front-End', 'Software', '.NET', 'WebServices', 'V-Cycle', 'GMC', 'Bank'],
    contact: [
      {
        id: '0',
        name: 'David De Mas',
        title: 'Associate Director',
      },
      {
        id: '1',
        name: 'Laurent Prette',
        title: 'Deputy Head of IT division',
      },
    ],
  },
  {
    id: '1',
    company: 'Bouygues',
    title: 'Embedded Systems Engineer',
    actions: ['Client Spuerkeess', 'Signing Pad', 'Corona'],
    outcomes: ['Client en agence peuvent signer par signingpad', 'Moins de papier via le moteur'],
    startDate: '2019-02-15',
    endDate: 'Present',
    tags: ['Front-End', 'Software', '.NET', 'WebServices', 'V-Cycle', 'GMC', 'Bank'],
    contact: [
      {
        id: '0',
        name: 'David De Mas',
        email: 'david.demas@davidson.eu',
        title: 'Associate Director',
      },
      {
        id: '1',
        name: 'Laurent Prette',
        email: 'l.prette@spuerkess.lu',
        title: 'Deputy Head of IT division',
      },
    ],
  },
  {
    id: '2',
    company: 'Cloudzen',
    title: 'Software Engineer',
    actions: ['Client Spuerkeess', 'Signing Pad', 'Corona'],
    outcomes: ['Client en agence peuvent signer par signingpad', 'Moins de papier via le moteur'],
    startDate: '2019-02-15',
    endDate: 'Present',
    tags: ['Front-End', 'Software', '.NET', 'WebServices', 'V-Cycle', 'GMC', 'Bank'],
    contact: [
      {
        id: '0',
        name: 'David De Mas',
        email: 'david.demas@davidson.eu',
        title: 'Associate Director',
      },
      {
        id: '1',
        name: 'Laurent Prette',
        email: 'l.prette@spuerkess.lu',
        title: 'Deputy Head of IT division',
      },
    ],
  },
  {
    id: '3',
    company: 'Everysens',
    title: 'Front-End Engineer',
    actions: ['Client Spuerkeess', 'Signing Pad', 'Corona'],
    outcomes: ['Client en agence peuvent signer par signingpad', 'Moins de papier via le moteur'],
    startDate: '2019-02-15',
    endDate: 'Present',
    tags: ['Front-End', 'Software', '.NET', 'WebServices', 'V-Cycle', 'GMC', 'Bank'],
    contact: [
      {
        id: '0',
        name: 'David De Mas',
        email: 'david.demas@davidson.eu',
        title: 'Associate Director',
      },
      {
        id: '1',
        name: 'Laurent Prette',
        email: 'l.prette@spuerkess.lu',
        title: 'Deputy Head of IT division',
      },
    ],
  },
  {
    id: '4',
    company: 'E.I.E',
    title: 'Assistant Quality Health and Security Manager',
    actions: ['Client Spuerkeess', 'Signing Pad', 'Corona'],
    outcomes: ['Client en agence peuvent signer par signingpad', 'Moins de papier via le moteur'],
    startDate: '2019-02-15',
    endDate: 'Present',
    tags: ['Front-End', 'Software', '.NET', 'WebServices', 'V-Cycle', 'GMC', 'Bank'],
    contact: [
      {
        id: '0',
        name: 'David De Mas',
        email: 'david.demas@davidson.eu',
        title: 'Associate Director',
      },
      {
        id: '1',
        name: 'Laurent Prette',
        email: 'l.prette@spuerkess.lu',
        title: 'Deputy Head of IT division',
      },
    ],
  },
  {
    id: '5',
    company: 'Ozanam',
    title: 'Full Stack Developer',
    actions: ['Client Spuerkeess', 'Signing Pad', 'Corona'],
    outcomes: ['Client en agence peuvent signer par signingpad', 'Moins de papier via le moteur'],
    startDate: '2019-02-15',
    endDate: 'Present',
    tags: ['Front-End', 'Software', '.NET', 'WebServices', 'V-Cycle', 'GMC', 'Bank'],
    contact: [
      {
        id: '0',
        name: 'David De Mas',
        email: 'david.demas@davidson.eu',
        title: 'Associate Director',
      },
      {
        id: '1',
        name: 'Laurent Prette',
        email: 'l.prette@spuerkess.lu',
        title: 'Deputy Head of IT division',
      },
    ],
  },
]

export default experiencesData
