export { default as SEO } from './SEO'
export { default as Main } from './Main'
export { default as Button } from './Button'
export { default as Map } from './Map'
export { default as Modal } from './Modal'
